Este proyecto fue enfocado a un refugio de perros

este es el link de netlify: https://animated-conkies-618a8f.netlify.app/

espero que sea de su agrado y perdon por la demora

enlace para el repositoio en git : https://github.com/Davidzul/landding-page

y aqui esta el link de la pagina en la plataforma git y que la verdad no se ve bien a comparacion con la plataforma netlify : https://davidzul.github.io/landding-page/
